# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\x12\tmapReduce\"\x14\n\x12WorkerReadyRequest\"\x15\n\x13WorkerReadyResponse\"9\n\x0fRegisterRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\".\n\x10RegisterResponse\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\n\n\x02id\x18\x05 \x01(\t\"\xcc\x01\n\x11SubmissionRequest\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\n\n\x02id\x18\x05 \x01(\t\x12\x12\n\noutputPath\x18\x07 \x01(\t\x12\x44\n\x0creducerPaths\x18\x06 \x03(\x0b\x32..mapReduce.SubmissionRequest.ReducerPathsEntry\x1a\x33\n\x11ReducerPathsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x14\n\x12SubmissionResponse2\xec\x01\n\x04Main\x12\x45\n\x08register\x12\x1a.mapReduce.RegisterRequest\x1a\x1b.mapReduce.RegisterResponse\"\x00\x12M\n\x0csubmitResult\x12\x1c.mapReduce.SubmissionRequest\x1a\x1d.mapReduce.SubmissionResponse\"\x00\x12N\n\x0bworkerReady\x12\x1d.mapReduce.WorkerReadyRequest\x1a\x1e.mapReduce.WorkerReadyResponse\"\x00\x42 \n\nmap-reduceB\tMapReduceP\x01\xa2\x02\x04\x44SCDb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\nmap-reduceB\tMapReduceP\001\242\002\004DSCD'
  _SUBMISSIONREQUEST_REDUCERPATHSENTRY._options = None
  _SUBMISSIONREQUEST_REDUCERPATHSENTRY._serialized_options = b'8\001'
  _WORKERREADYREQUEST._serialized_start=25
  _WORKERREADYREQUEST._serialized_end=45
  _WORKERREADYRESPONSE._serialized_start=47
  _WORKERREADYRESPONSE._serialized_end=68
  _REGISTERREQUEST._serialized_start=70
  _REGISTERREQUEST._serialized_end=127
  _REGISTERRESPONSE._serialized_start=129
  _REGISTERRESPONSE._serialized_end=175
  _SUBMISSIONREQUEST._serialized_start=178
  _SUBMISSIONREQUEST._serialized_end=382
  _SUBMISSIONREQUEST_REDUCERPATHSENTRY._serialized_start=331
  _SUBMISSIONREQUEST_REDUCERPATHSENTRY._serialized_end=382
  _SUBMISSIONRESPONSE._serialized_start=384
  _SUBMISSIONRESPONSE._serialized_end=404
  _MAIN._serialized_start=407
  _MAIN._serialized_end=643
# @@protoc_insertion_point(module_scope)
