# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reducer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreducer.proto\x12\tmapReduce\"\x80\x01\n\rReduceRequest\x12<\n\ninputpaths\x18\x03 \x03(\x0b\x32(.mapReduce.ReduceRequest.InputpathsEntry\x1a\x31\n\x0fInputpathsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\" \n\x0eReduceResponse\x12\x0e\n\x06status\x18\x02 \x01(\t2J\n\x07Reducer\x12?\n\x06reduce\x12\x18.mapReduce.ReduceRequest\x1a\x19.mapReduce.ReduceResponse\"\x00\x42\x1f\n\nmap-reduceB\tMapReduceP\x01\xa2\x02\x03\x44SCb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reducer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\nmap-reduceB\tMapReduceP\001\242\002\003DSC'
  _REDUCEREQUEST_INPUTPATHSENTRY._options = None
  _REDUCEREQUEST_INPUTPATHSENTRY._serialized_options = b'8\001'
  _REDUCEREQUEST._serialized_start=29
  _REDUCEREQUEST._serialized_end=157
  _REDUCEREQUEST_INPUTPATHSENTRY._serialized_start=108
  _REDUCEREQUEST_INPUTPATHSENTRY._serialized_end=157
  _REDUCERESPONSE._serialized_start=159
  _REDUCERESPONSE._serialized_end=191
  _REDUCER._serialized_start=193
  _REDUCER._serialized_end=267
# @@protoc_insertion_point(module_scope)
