# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import discord_pb2 as discord__pb2


class DiscordStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinServer = channel.unary_unary(
                '/discord.Discord/JoinServer',
                request_serializer=discord__pb2.ClientIdentifier.SerializeToString,
                response_deserializer=discord__pb2.ResponseStatus.FromString,
                )
        self.LeaveServer = channel.unary_unary(
                '/discord.Discord/LeaveServer',
                request_serializer=discord__pb2.ClientIdentifier.SerializeToString,
                response_deserializer=discord__pb2.ResponseStatus.FromString,
                )
        self.PublishArticles = channel.unary_unary(
                '/discord.Discord/PublishArticles',
                request_serializer=discord__pb2.ArticleFormat.SerializeToString,
                response_deserializer=discord__pb2.ResponseStatus.FromString,
                )
        self.GetArticles = channel.unary_stream(
                '/discord.Discord/GetArticles',
                request_serializer=discord__pb2.ArticleTag.SerializeToString,
                response_deserializer=discord__pb2.ArticleFormat.FromString,
                )
        self.PingPong = channel.unary_unary(
                '/discord.Discord/PingPong',
                request_serializer=discord__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=discord__pb2.HealthCheckResponse.FromString,
                )


class DiscordServicer(object):
    """Missing associated documentation comment in .proto file."""

    def JoinServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishArticles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArticles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PingPong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscordServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinServer': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinServer,
                    request_deserializer=discord__pb2.ClientIdentifier.FromString,
                    response_serializer=discord__pb2.ResponseStatus.SerializeToString,
            ),
            'LeaveServer': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveServer,
                    request_deserializer=discord__pb2.ClientIdentifier.FromString,
                    response_serializer=discord__pb2.ResponseStatus.SerializeToString,
            ),
            'PublishArticles': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishArticles,
                    request_deserializer=discord__pb2.ArticleFormat.FromString,
                    response_serializer=discord__pb2.ResponseStatus.SerializeToString,
            ),
            'GetArticles': grpc.unary_stream_rpc_method_handler(
                    servicer.GetArticles,
                    request_deserializer=discord__pb2.ArticleTag.FromString,
                    response_serializer=discord__pb2.ArticleFormat.SerializeToString,
            ),
            'PingPong': grpc.unary_unary_rpc_method_handler(
                    servicer.PingPong,
                    request_deserializer=discord__pb2.HealthCheckRequest.FromString,
                    response_serializer=discord__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'discord.Discord', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Discord(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/discord.Discord/JoinServer',
            discord__pb2.ClientIdentifier.SerializeToString,
            discord__pb2.ResponseStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LeaveServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/discord.Discord/LeaveServer',
            discord__pb2.ClientIdentifier.SerializeToString,
            discord__pb2.ResponseStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PublishArticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/discord.Discord/PublishArticles',
            discord__pb2.ArticleFormat.SerializeToString,
            discord__pb2.ResponseStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetArticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/discord.Discord/GetArticles',
            discord__pb2.ArticleTag.SerializeToString,
            discord__pb2.ArticleFormat.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PingPong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/discord.Discord/PingPong',
            discord__pb2.HealthCheckRequest.SerializeToString,
            discord__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
