# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discord.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdiscord.proto\x12\x07\x64iscord\"\xec\x01\n\rArticleFormat\x12\x10\n\x06SPORTS\x18\x01 \x01(\x08H\x00\x12\x11\n\x07\x46\x41SHION\x18\x02 \x01(\x08H\x00\x12\x12\n\x08POLITICS\x18\x03 \x01(\x08H\x00\x12\x0e\n\x06\x41uthor\x18\x04 \x01(\t\x12\x0f\n\x07\x43ontent\x18\x05 \x01(\t\x12\x16\n\tTimestamp\x18\x06 \x01(\tH\x01\x88\x01\x01\x12\x33\n\x0bPublisherId\x18\x08 \x01(\x0b\x32\x19.discord.ClientIdentifierH\x02\x88\x01\x01\x12\x0e\n\x06status\x18\n \x01(\tB\x06\n\x04TypeB\x0c\n\n_TimestampB\x0e\n\x0c_PublisherId\"\xe5\x01\n\nArticleTag\x12\x10\n\x06SPORTS\x18\x01 \x01(\x08H\x00\x12\x11\n\x07\x46\x41SHION\x18\x02 \x01(\x08H\x00\x12\x12\n\x08POLITICS\x18\x03 \x01(\x08H\x00\x12\x13\n\x06\x41uthor\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07\x43ontent\x18\x05 \x01(\tH\x02\x88\x01\x01\x12\x16\n\tTimestamp\x18\x06 \x01(\tH\x03\x88\x01\x01\x12.\n\x0bPublisherId\x18\x08 \x01(\x0b\x32\x19.discord.ClientIdentifierB\x06\n\x04TypeB\t\n\x07_AuthorB\n\n\x08_ContentB\x0c\n\n_Timestamp\" \n\x0eResponseStatus\x12\x0e\n\x06status\x18\x07 \x01(\t\"\x1e\n\x10\x43lientIdentifier\x12\n\n\x02id\x18\x08 \x01(\t\",\n\x13HealthCheckResponse\x12\x15\n\rservingstatus\x18\t \x01(\x08\"\x14\n\x12HealthCheckRequest2\xe1\x02\n\x07\x44iscord\x12\x42\n\nJoinServer\x12\x19.discord.ClientIdentifier\x1a\x17.discord.ResponseStatus\"\x00\x12\x43\n\x0bLeaveServer\x12\x19.discord.ClientIdentifier\x1a\x17.discord.ResponseStatus\"\x00\x12\x44\n\x0fPublishArticles\x12\x16.discord.ArticleFormat\x1a\x17.discord.ResponseStatus\"\x00\x12>\n\x0bGetArticles\x12\x13.discord.ArticleTag\x1a\x16.discord.ArticleFormat\"\x00\x30\x01\x12G\n\x08PingPong\x12\x1b.discord.HealthCheckRequest\x1a\x1c.discord.HealthCheckResponse\"\x00\x42\x1f\n\x07\x64iscordB\x0c\x44iscordProtoP\x01\xa2\x02\x03\x44SCb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'discord_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\007discordB\014DiscordProtoP\001\242\002\003DSC'
  _ARTICLEFORMAT._serialized_start=27
  _ARTICLEFORMAT._serialized_end=263
  _ARTICLETAG._serialized_start=266
  _ARTICLETAG._serialized_end=495
  _RESPONSESTATUS._serialized_start=497
  _RESPONSESTATUS._serialized_end=529
  _CLIENTIDENTIFIER._serialized_start=531
  _CLIENTIDENTIFIER._serialized_end=561
  _HEALTHCHECKRESPONSE._serialized_start=563
  _HEALTHCHECKRESPONSE._serialized_end=607
  _HEALTHCHECKREQUEST._serialized_start=609
  _HEALTHCHECKREQUEST._serialized_end=629
  _DISCORD._serialized_start=632
  _DISCORD._serialized_end=985
# @@protoc_insertion_point(module_scope)
