# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import registry_pb2 as registry__pb2


class RegistryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/discord.Registry/Register',
                request_serializer=registry__pb2.ServerAddress.SerializeToString,
                response_deserializer=registry__pb2.RegistryResponseStatus.FromString,
                )
        self.GetServerList = channel.unary_stream(
                '/discord.Registry/GetServerList',
                request_serializer=registry__pb2.EnquireServers.SerializeToString,
                response_deserializer=registry__pb2.LiveServer.FromString,
                )


class RegistryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=registry__pb2.ServerAddress.FromString,
                    response_serializer=registry__pb2.RegistryResponseStatus.SerializeToString,
            ),
            'GetServerList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetServerList,
                    request_deserializer=registry__pb2.EnquireServers.FromString,
                    response_serializer=registry__pb2.LiveServer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'discord.Registry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Registry(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/discord.Registry/Register',
            registry__pb2.ServerAddress.SerializeToString,
            registry__pb2.RegistryResponseStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/discord.Registry/GetServerList',
            registry__pb2.EnquireServers.SerializeToString,
            registry__pb2.LiveServer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
