# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eregistry.proto\x12\x06quorum\")\n\rServerAddress\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"#\n\x0e\x45nquireServers\x12\x11\n\toperation\x18\x03 \x01(\t2\x8a\x01\n\x08Registry\x12:\n\x08Register\x12\x15.quorum.ServerAddress\x1a\x15.quorum.ServerAddress\"\x00\x12\x42\n\rGetServerList\x12\x16.quorum.EnquireServers\x1a\x15.quorum.ServerAddress\"\x00\x30\x01\x42!\n\x0fquorum-protocolB\x06QuorumP\x01\xa2\x02\x03\x44SCb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registry_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\017quorum-protocolB\006QuorumP\001\242\002\003DSC'
  _SERVERADDRESS._serialized_start=26
  _SERVERADDRESS._serialized_end=67
  _ENQUIRESERVERS._serialized_start=69
  _ENQUIRESERVERS._serialized_end=104
  _REGISTRY._serialized_start=107
  _REGISTRY._serialized_end=245
# @@protoc_insertion_point(module_scope)
