# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x06quorum\"*\n\x0eReplicaAddress\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"\x1e\n\x0cJoinResponse\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x1b\n\x0bReadRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"N\n\x0cReadResponse\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x0f\n\x07version\x18\x05 \x01(\t\";\n\x0cWriteRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\">\n\rWriteResponse\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x05 \x01(\t\"\x1d\n\rDeleteRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\" \n\x0e\x44\x65leteResponse\x12\x0e\n\x06status\x18\x02 \x01(\t2\xed\x01\n\x06Server\x12\x33\n\x04Read\x12\x13.quorum.ReadRequest\x1a\x14.quorum.ReadResponse\"\x00\x12\x36\n\x05Write\x12\x14.quorum.WriteRequest\x1a\x15.quorum.WriteResponse\"\x00\x12\x39\n\x06\x44\x65lete\x12\x15.quorum.DeleteRequest\x1a\x16.quorum.DeleteResponse\"\x00\x12;\n\tNewJoinee\x12\x16.quorum.ReplicaAddress\x1a\x14.quorum.JoinResponse\"\x00\x42!\n\x0fquorum-protocolB\x06QuorumP\x01\xa2\x02\x03\x44SCb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\017quorum-protocolB\006QuorumP\001\242\002\003DSC'
  _REPLICAADDRESS._serialized_start=24
  _REPLICAADDRESS._serialized_end=66
  _JOINRESPONSE._serialized_start=68
  _JOINRESPONSE._serialized_end=98
  _READREQUEST._serialized_start=100
  _READREQUEST._serialized_end=127
  _READRESPONSE._serialized_start=129
  _READRESPONSE._serialized_end=207
  _WRITEREQUEST._serialized_start=209
  _WRITEREQUEST._serialized_end=268
  _WRITERESPONSE._serialized_start=270
  _WRITERESPONSE._serialized_end=332
  _DELETEREQUEST._serialized_start=334
  _DELETEREQUEST._serialized_end=363
  _DELETERESPONSE._serialized_start=365
  _DELETERESPONSE._serialized_end=397
  _SERVER._serialized_start=400
  _SERVER._serialized_end=637
# @@protoc_insertion_point(module_scope)
